language: node_js
node_js:
  - 4
env:
  global:
    secure: mdLjWe6lUisAguAutLFcqM1jI1x8tZ8Cn7lzY2YUojhocUEaO3riZ/a9hjoZ1mrz/lYcsbLLI5zjjNXcGSNTAekYa4OdEWfrKWZxMZ91A2KnRkjTja+d+k2IZhjVGzjyG23sIz7uCLSPjR/IKGoFTn8DzgREkhSpSbRuCMSqSzTOWac7mYafGytAPVPOI4XqLNBjrImM27jzPSSAcJNKxsEWJ9mzDvhgccpZEIL17x0jwRnAEesCGRk6t0LvCpqyc1IBouwdQHWLRQ2+I1SZW5HjI+7RrVpRmIzJGlruO30HmYh/MblfAvPCgUBmkx2iw4PrhGD75hnmed0G2c3KjisA0Nom/P1RelJeTcu3l+KwvCeuF1nuR9aeMAefKRIRmUAAjpDPWfjIipVJ6mxnn33bltiBnmHtPf3u/dpjpMXGYPy16fMPzq9avRiD9MFiQvXYKHsIPjAnxlcAbtiEWL69PpiJceKufoE2J0+ujy+KZembOq/um9aLZpz5f2C+Rnx1YwSpmIBvVaIRKSydfRuuzCs380RpFZpiWw5tYTfgMFqAYKQBZ6IXX0DNbRjBT7I5c2QlHWuSjq2xApWiKm1xhBCg2pJRNQRWtDSmrivCxP2L6LkftOjS36O7SLby7r+HqXHkJglzzxAWm4NKpmjMG3McPGtzS+7YJHjtmP0=
